# Generated by Django 5.2.8 on 2025-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaps', '0002_invoiceitem_consumed_invoiceitem_end_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='code',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas')], max_length=20, null=True),
        ),
    ]
