# Generated by Django 5.2.8 on 2025-11-30 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaps', '0003_taxtype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='skaps.meter'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='period_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='skaps.periodtax'),
        ),
    ]
