# Generated by Django 5.2.8 on 2025-12-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaps', '0004_invoiceitem_meter_invoiceitem_period_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxtype',
            name='code',
        ),
        migrations.AddField(
            model_name='meter',
            name='ser_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('water', 'Water'), ('gas', 'Gas')], help_text="Used only if distribution_type='proportional'", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='unit',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
