# Generated by Django 5.2.8 on 2025-12-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skaps', '0005_remove_taxtype_code_meter_ser_num_taxtype_meter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='ser_num',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serial number'),
        ),
    ]
